#!/bin/bash

set -e

SCRIPT_DIR="$(dirname "$(readlink -f $0)")"
WINEDRIVE="${SCRIPT_DIR}/winedrive"
if ! [ -e "$WINEDRIVE" ]; then
    mkdir -p "$WINEDRIVE"
    cp "${SCRIPT_DIR}/user.reg" "$WINEDRIVE/"
fi

exec scripts/x11docker -h --user root --gpu --pulse \
    -- -v "$(pwd)/winedrive":/wine -v "$(pwd)/EI":/EI \
    -- ei

#
# Old method:
#
# pulse-client.conf:
# default-server = unix:/run/user/0/pulse/native
# autospawn = no
# daemon-binary = /bin/true
# enable-shm = false
#
# run.sh
# docker run -it --rm \
#    -e DISPLAY \
#    -e PULSE_SERVER="unix:${XDG_RUNTIME_DIR}/pulse/native" \
#    --device /dev/snd \
#    --device /dev/dri \
#    --device /dev/vga_arbiter \
#    --volume "${SCRIPT_DIR}/pulse-client.conf":/etc/pulse/client.conf \
#    -v "${XDG_RUNTIME_DIR}/pulse/native":"${XDG_RUNTIME_DIR}/pulse/native" \
#    -v "$HOME/.config/pulse/cookie":/root/.config/pulse/cookie \
#    -v "$HOME/.Xauthority:/root/.Xauthority:rw" \
#    -v /tmp/.X11-unix/X0:/tmp/.X11-unix/X0 \
#    -v "${SCRIPT_DIR}/winedrive":/wine \
#    -v "${SCRIPT_DIR}/EI:/EI:rw" \
#    "$@"
#
